ALTER TABLE strava_tokens 
  ADD COLUMN IF NOT EXISTS username VARCHAR(255),
  ADD COLUMN IF NOT EXISTS profile_picture TEXT,
  ADD COLUMN IF NOT EXISTS athlete_name VARCHAR(255),
  ADD COLUMN IF NOT EXISTS last_sync TIMESTAMP WITH TIME ZONE;

ALTER TABLE workouts 
  ADD COLUMN IF NOT EXISTS calories NUMERIC(10, 2),
  ADD COLUMN IF NOT EXISTS elevation NUMERIC(10, 2),
  ADD COLUMN IF NOT EXISTS average_hr NUMERIC(10, 2),
  ADD COLUMN IF NOT EXISTS average_pace VARCHAR(50),
  ADD COLUMN IF NOT EXISTS average_speed NUMERIC(10, 2),
  ADD COLUMN IF NOT EXISTS moving_time INTEGER,
  ADD COLUMN IF NOT EXISTS elapsed_time INTEGER,
  ADD COLUMN IF NOT EXISTS gear VARCHAR(255),
  ADD COLUMN IF NOT EXISTS gps_polyline TEXT;
